### ISSUE TITLE
Assignment 2

### ISSUE THREAD

**Issue by anzonyquispe** [alexanderquispe/MediaLab_Summer_Python#42]
Dear all,

1. Follow the instructions in the Jupyter Notebook (JN) named as [Assignment_2](https://github.com/alexanderquispe/MediaLab_Summer_Python/blob/main/assignments/assignment2/Assignment_2.ipynb).  
2. Each group must create their branch named `group_#_ass_2_2024` (group_1_ass_2_2024) and save their results in the [Assignment_2](https://github.com/alexanderquispe/MediaLab_Summer_Python/blob/main/assignments/assignment2) folder. Name your JN like your branch.
3.  Your `Pull request` should be linked to this issue.
4. All the questions about the assignment should be posted in this issue. 
5. Follow the same procedure as in the previous assignment. Only the RM (Repository Maintainer) should do the final merge. Since, most of you will divide the work, the RP should make a summary of the work done by each member as a final comment before merging your work to the main branch. For the rest of the members be very explicit and detailed when you comment your work. Take this assignment as a simulacro of real work. 
6. The RP is the lead of all the assignments and will be the same during the entire course. If any member does not work, we should be able to see it clearly in the RP's comments and in the branch's commit history. 
7. If we do not see any commit of a member, we will consider that it did not work and will not be graded and get 0 automatically.

**Deadline: 01/10/24 - 11:59am**

**Comment by marcoerqui95** [comment]
**Assignment #46** 

- Nathaly's part was the first 5 exercises.
- Marco's part was the last 5 exercises (pandas)

**Comment by gnl0001** [comment]
Group 8 Assignment 2 #52 
Assignment distribution:
Hanz: exercises 1-3 from Dictionaries and 1 from Pandas.
Gabriela: Exercises 4-5 Dictionaries and exercises 2-5 from Pandas
Valeria is having problems with Git-hub so she couldn't participate properly in the assingment, but she is getting technical assistance soon.

**Comment by marcoerqui95** [comment]
Dear @anzonyquispe,

Here you will find our Assignment 2 with the requested changes #66.

@nathalybelapatino  part was the first 5 exercises.
@marcoerqui95 (me) my part was the last 5 exercises (pandas).
